services:
  flask-app:
    # 이 부분은 배포 시점에 실제 ECR 이미지 주소로 교체됩니다.
    image: IMAGE_PLACEHOLDER
    ports:
      - "5001:5001"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=root
      - MONGO_PASS=password
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    healthcheck: # <--- 이 부분을 추가합니다.
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data: